apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: dev

components:
  - ../../base/argocd

helmCharts:
  - name: argo-cd
    namespace: argocd
    version: 7.8.11
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: ../../base/argocd/helm-values/argocd-values.yaml
    includeCRDs: true

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      namespace: argocd
      name: argocd
    path: patches/apps/argocd-app-patch.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      namespace: argocd
      name: django-app
    path: patches/apps/django-app-patch.yaml
