- name: Get kubeconfig value
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kc_slurp
  become: true

- ansible.builtin.set_fact:
    original_kubeconfig: "{{ kc_slurp['content'] | b64decode | from_yaml }}"
  no_log: true

- ansible.utils.update_fact:
    updates:
      - path: original_kubeconfig.clusters[0].cluster.server
        value: "https://{{ inventory_hostname }}:6443"
      - path: original_kubeconfig.contexts[0].name
        value: "{{ k3s_fqdn }}"
      - path: original_kubeconfig.current-context
        value: "{{ k3s_fqdn }}"
  register: kubeconfig_updated
  no_log: true

- name: Write kubeconfig in localhost
  ansible.builtin.copy:
    content: "{{ kubeconfig_updated.original_kubeconfig | to_nice_yaml }}"
    dest: "{{ kubeconfig }}"
    mode: "0644"
  delegate_to: localhost
  no_log: true
